server:
  port: 8080

spring:
  application:
    name: vg-quality-challenge

logging:
  level:
    pe.edu.vallegrande: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"